repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"
          - "javascript"
      - id: check-byte-order-marker
      - id: check-json
      - id: forbid-new-submodules
      - id: check-added-large-files
        args: ["--maxkb=2500"]
      - id: check-merge-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"

      - id: forbid-tabs
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"

  # Set to select only obvious errors
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        args:
          - "--fix"

      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        # Exclude files with a regex
        # exclude:
